language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
install: "pip install -r requirements.txt && pip install -r requirements-dev.txt"
os:
 - linux
notifications:
   email: false
script:
  - py.test tests/
